### ISSUE TITLE
RPG HUD thirst bar not rendering

### ISSUE THREAD

**Issue by SebastienBruckert** [8-BrickDMG/Affinity-Infinity-Two#1]
Hello, I don't know why, I eat everything, berries, raw beef, gardens from pam's harvestcraft... My food bar is full at 20, but I'm still loosing life and can't run after maybe 10min of game. Then, in hardcore mode, I starve to death :/

**Comment by thebrightspark** [comment]
What about your thirst level?

**Comment by 8-BrickDMG** [comment]
It may be the thirst level. I noticed with the RPG HUD that the thirst bar isn't rendering. This will be sorted in the next update.
For now you can disable that mod. Will keep this open till the next update.

**Comment by SebastienBruckert** [comment]
Oh, so there is thirst ! Good to know, yeah I'll disable RPG HUD then thank you for the quick answer

**Comment by 8-BrickDMG** [comment]
Removed mod in the pending update. Check Curseforge for the download.

**Comment by 8-BrickDMG** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/nMey8EVl/12-test)
