### ISSUE TITLE
Snow bricks craft / Preston

### ISSUE THREAD

**Issue by SebastienBruckert** [8-BrickDMG/Affinity-Infinity-Two#2]
Hello, me again ^^

The craft for snow bricks is remplaced by the one for Preston, because it's the same craft. So there is no way of getting snow bricks sadly :/
Thr craft is a 2*2 square of snow block

**Comment by 8-BrickDMG** [comment]
Added 'No More Recipe Conflict' in the pending update. You'll be able to use a button under the output to choose the different  item you want.
