### ISSUE TITLE
Add recipe for Spectre Saplings

### ISSUE THREAD

**Issue by thebrightspark** [8-BrickDMG/Affinity-Infinity-Two#4]
To craft a Spectre Sapling you normally need to right click an Oak Sapling in the world with Ectoplasm. But it's not possible to place an Oak Sapling.

We need a recipe for Oak Sapling + Ectoplasm = Spectre Sapling

**Comment by 8-BrickDMG** [comment]
Recipe has been added to craft the sapling in the 1.5 update.
